### ISSUE TITLE
Pulling images from other docker registries seems not to be working

### ISSUE THREAD

**Issue by bartvanb** [IKNL/vantage6-node#56]
When the user specifies an algorithm from a different docker registry than harbor2, the pulling of the image does not work. This requires the user to manually pull the docker image before running the algorithm.

This may be tested with the v6-node-to-node-diagnostics algorithm from the CARRIER package.

**Comment by dsmits** [comment]
In my experience this is only the case when it is the first time the node pulls the image.
For some reason, when I pull the image manually first, the node will later be able to pull a more up-to-date version of the image if the local one is outdated.

**Comment by dsmits** [comment]
This is the error that I get:
```
2022-01-03 15:54:36 - node - ERROR - 404 Client Error: Not Found ("no such image: harbor2.vantage6.ai/testing/v6-test-py: No such image: harbor2.vantage6.ai/testing/v6-test-py:latest")
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
response.raise_for_status()
File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/images/harbor2.vantage6.ai/testing/v6-test-py/json



During handling of the above exception, another exception occurred:



Traceback (most recent call last):
File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 714, in run_forever
self.__start_task(task)
File "/vantage6/vantage6-node/vantage6/node/__init__.py", line 339, in __start_task
token=token
File "/vantage6/vantage6-node/vantage6/node/docker/docker_manager.py", line 261, in run
algorithm_env=self.algorithm_env
File "/vantage6/vantage6-node/vantage6/node/docker/task_manager.py", line 178, in run
vpn_port = self._run_algorithm()
File "/vantage6/vantage6-node/vantage6/node/docker/task_manager.py", line 222, in _run_algorithm
algo_image_name=self.image
File "/vantage6/vantage6-node/vantage6/node/docker/vpn_manager.py", line 181, in forward_vpn_traffic
helper_container, algo_image_name)
File "/vantage6/vantage6-node/vantage6/node/docker/vpn_manager.py", line 257, in _forward_traffic_to_algorithm
algorithm_port = self._find_exposed_port(algo_image_name)
File "/vantage6/vantage6-node/vantage6/node/docker/vpn_manager.py", line 285, in _find_exposed_port
n2n_image = self.docker.images.get(image)
File "/usr/local/lib/python3.7/site-packages/docker/models/images.py", line 316, in get
return self.prepare_model(self.client.api.inspect_image(name))
File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
return f(self, resource_id, *args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/docker/api/image.py", line 246, in inspect_image
self._get(self._url("/images/{0}/json", image)), True
File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 267, in _result
self._raise_for_status(response)
File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
raise create_api_error_from_http_exception(e)
File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("no such image: harbor2.vantage6.ai/testing/v6-test-py: No such image: harbor2.vantage6.ai/testing/v6-test-py:latest")

```

**Comment by bartvanb** [comment]
The problem was that we already tried to access the image (for VPN setup - reading ports and port labels) while it had not yet been pulled.

Fixed this by downloading the image sooner.
