### ISSUE TITLE
Issue starting V6 server after upgrading to 3.2.0

### ISSUE THREAD

**Issue by casparvl** [IKNL/vantage6-node#87]
I upgraded to 3.2.0, but then I got:
```
[info]  - Run Docker container
Traceback (most recent call last):
  File "/home/cvanleeuwe/.local/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/home/cvanleeuwe/.local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.35/containers/adb074e67e5da4f56aae5a25d9b6ffd938cb6fa8dacd313112f056d54f40a3f9/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cvanleeuwe/.local/bin/vserver", line 8, in <module>
    sys.exit(cli_server())
  File "/home/cvanleeuwe/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/cvanleeuwe/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/cvanleeuwe/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cvanleeuwe/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cvanleeuwe/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/cvanleeuwe/.local/lib/python3.8/site-packages/vantage6/cli/server.py", line 98, in func_with_context
    return func(ctx, *args, **kwargs)
  File "/home/cvanleeuwe/.local/lib/python3.8/site-packages/vantage6/cli/server.py", line 233, in cli_server_start
    container = docker_client.containers.run(
  File "/home/cvanleeuwe/.local/lib/python3.8/site-packages/docker/models/containers.py", line 809, in run
    container.start()
  File "/home/cvanleeuwe/.local/lib/python3.8/site-packages/docker/models/containers.py", line 400, in start
    return self.client.api.start(self.id, **kwargs)
  File "/home/cvanleeuwe/.local/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/cvanleeuwe/.local/lib/python3.8/site-packages/docker/api/container.py", line 1095, in start
    self._raise_for_status(res)
  File "/home/cvanleeuwe/.local/lib/python3.8/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/cvanleeuwe/.local/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "uwsgi": executable file not found in $PATH: unknown")
```
Does this ring a bell? Not sure if the first or the second Error is the actual one... 

N.B. There was no `uwsgi` in my `PATH` (there wasn't before either when I ran with V6 3.1.0 by the way), so I tried a `pip install uwsgi`. Now I do have that executable in my `PATH`, but I still get the same issue when starting the V6 server.

**Comment by casparvl** [comment]
Yes, that was it, it works now, thanks!
